---
- name: Stat VDDK library
  stat:
    path: "{{ v2v_vddk_install_dir }}/vmware-vix-disklib-distrib/lib64/libvixDiskLib.so"
  ignore_errors: "yes"
  register: stat_vddk_library

- name: Stat VDDK nbdkit plugin
  stat:
    path: "/usr/lib64/nbdkit/plugins/nbdkit-vddk-plugin.so"
  ignore_errors: "yes"
  register: stat_nbdkit_plugin

- name: Set VDDK and nbdkit facts
  set_fact:
    v2v_vddk_library_installed: "{{ stat_vddk_library.stat.exists }}"
    v2v_nbdkit_plugin_installed: "{{ stat_nbdkit_plugin.stat.exists }}"
