---
- name: Validate RHV host -- RHV Guest Tools
  command: /usr/bin/virt-v2v-wrapper.py --check-rhv-guest-tools
  when: v2v_checks_override is not defined or not v2v_checks_override
  changed_when: false
