---
- name: Install packages for OpenStack appliance (EL7)
  yum:
    name:
      - python2-openstackclient
      - virtio-win
      - python-six
    state: "{{ v2v_yum_check }}"
  when: ansible_distribution_major_version == "7"

- name: Install packages for OpenStack appliance (EL8)
  yum:
    name:
      - python3-openstackclient
      - python3-six
      - virtio-win
    state: "{{ v2v_yum_check }}"
  when: ansible_distribution_major_version == "8"

- name: Create cron job for log cleanup
  copy:
    src: etc/cron.daily/virt-v2v-logs
    dest: /etc/cron.daily/virt-v2v-logs
    owner: root
    group: root
    mode: 0755
