---
- name: Stat VDDK library
  stat:
    path: "{{ v2v_vddk_install_dir }}/vmware-vix-disklib-distrib/lib64/libvixDiskLib.so"
  ignore_errors: "yes"
  register: stat_vddk_library

- name: Set VDDK facts
  set_fact:
    v2v_vddk_library_installed: "{{ stat_vddk_library.stat.exists }}"
