---
- name: Look for existing SSH private key file
  stat:
    path: "/root/.ssh/id_rsa"
  ignore_errors: "yes"
  register: stat_ssh_key

- block:
    - name: Check var v2v_ssh_private_key
      fail:
        msg: "No file named '/root/.ssh/id_rsa' found and no 'v2v_ssh_private_key' variable set"
      when:
        - "v2v_ssh_private_key is not defined"

    - name: Create .ssh directory
      file:
        path: "/root/.ssh"
        owner: "root"
        group: "root"
        mode: 0700
        state: directory

    - name: Create the SSH private key file
      copy:
        dest: "/root/.ssh/id_rsa"
        content: "{{ v2v_ssh_private_key }}"
        owner: "root"
        group: "root"
        mode: 0600

  when: not stat_ssh_key.stat.exists
