---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-disk1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
  nfs:
    path: /nfs/disk1
    server: 192.168.42.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-disk2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
  nfs:
    path: /nfs/disk2
    server: 192.168.42.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-temp
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
  nfs:
    path: /nfs/temp
    server: 192.168.42.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vddk
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
  nfs:
    path: /nfs/vddk
    server: 192.168.42.1
